name: EterniaBuilder
version: 1.0.0
main: io.github.humanrice.eterniabuilder
description: Auto Building Builder for the Eternia SMP
author: Aidan Mikhail
website: https://papermc.io
api-version: '26.1.2'